/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MAKESDR_RADIOPAYLOADS_PB_H_INCLUDED
#define PB_MAKESDR_RADIOPAYLOADS_PB_H_INCLUDED
#include <pb.h>
#include "RadioSettings.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _makesdr_RadioPayloadType {
    makesdr_RadioPayloadType_PAYLOAD_NONE = 0,
    makesdr_RadioPayloadType_PAYLOAD_SETTINGS_BASIC_RX = 1,
    makesdr_RadioPayloadType_PAYLOAD_SETTINGS_BASIC_IQ_RX = 2,
    makesdr_RadioPayloadType_PAYLOAD_SETTINGS_DUAL_IQ_RX = 3,
    makesdr_RadioPayloadType_PAYLOAD_SETTINGS_BASIC_RXTX = 4,
    makesdr_RadioPayloadType_PAYLOAD_SETTINGS_BASIC_IQ_RXTX = 5,
    makesdr_RadioPayloadType_PAYLOAD_SETTINGS_DUAL_IQ_RXTX = 6,
    makesdr_RadioPayloadType_PAYLOAD_SETTINGS_SPLIT_BAND_DUAL_IQ_RXTX = 7,
    makesdr_RadioPayloadType_PAYLOAD_META = 10,
    makesdr_RadioPayloadType_PAYLOAD_CACHE_BASIC = 20,
    makesdr_RadioPayloadType_PAYLOAD_CACHE_BASIC_IQ = 21,
    makesdr_RadioPayloadType_PAYLOAD_CACHE_DUAL = 22
} makesdr_RadioPayloadType;

typedef enum _makesdr_RadioPayloadPurpose {
    makesdr_RadioPayloadPurpose_PURPOSE_NONE = 0,
    makesdr_RadioPayloadPurpose_PURPOSE_MERGE = 1,
    makesdr_RadioPayloadPurpose_PURPOSE_REPLACE = 2
} makesdr_RadioPayloadPurpose;

/* Struct definitions */
typedef struct _makesdr_RadioPayloadHeaderPb {
    makesdr_RadioPayloadType payloadType;
} makesdr_RadioPayloadHeaderPb;

typedef struct _makesdr_RadioPayloadBasePb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
} makesdr_RadioPayloadBasePb;

typedef struct _makesdr_BasicRxSettingsPayloadPb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
    makesdr_RadioPayloadPurpose purpose;
    bool has_body;
    makesdr_BasicRxSettingsPb body;
} makesdr_BasicRxSettingsPayloadPb;

typedef struct _makesdr_BasicIqRxSettingsPayloadPb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
    makesdr_RadioPayloadPurpose purpose;
    bool has_body;
    makesdr_BasicIqRxSettingsPb body;
} makesdr_BasicIqRxSettingsPayloadPb;

typedef struct _makesdr_DualIqRxSettingsPayloadPb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
    makesdr_RadioPayloadPurpose purpose;
    bool has_body;
    makesdr_DualIqRxSettingsPb body;
} makesdr_DualIqRxSettingsPayloadPb;

typedef struct _makesdr_BasicRxTxSettingsPayloadPb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
    makesdr_RadioPayloadPurpose purpose;
    bool has_body;
    makesdr_BasicRxTxSettingsPb body;
} makesdr_BasicRxTxSettingsPayloadPb;

typedef struct _makesdr_BasicIqRxTxSettingsPayloadPb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
    makesdr_RadioPayloadPurpose purpose;
    bool has_body;
    makesdr_BasicIqRxTxSettingsPb body;
} makesdr_BasicIqRxTxSettingsPayloadPb;

typedef struct _makesdr_DualIqRxTxSettingsPayloadPb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
    makesdr_RadioPayloadPurpose purpose;
    bool has_body;
    makesdr_DualIqRxTxSettingsPb body;
} makesdr_DualIqRxTxSettingsPayloadPb;

typedef struct _makesdr_SplitBandDualIqRxTxSettingsPayloadPb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
    makesdr_RadioPayloadPurpose purpose;
    bool has_body;
    makesdr_SplitBandDualIqRxTxSettingsPb body;
} makesdr_SplitBandDualIqRxTxSettingsPayloadPb;

typedef struct _makesdr_RadioLookupPayloadPb {
    bool has_header;
    makesdr_RadioPayloadHeaderPb header;
    bool has_body;
    makesdr_RadioLookupPb body;
} makesdr_RadioLookupPayloadPb;

typedef struct _makesdr_RadioCacheBasicPayloadPb {
    makesdr_RadioPayloadType payloadType;
    bool has_body;
    makesdr_BasicBandSettingsCachePb body;
} makesdr_RadioCacheBasicPayloadPb;

typedef struct _makesdr_RadioCacheBasicIqPayloadPb {
    makesdr_RadioPayloadType payloadType;
    bool has_body;
    makesdr_BasicIqBandSettingsCachePb body;
} makesdr_RadioCacheBasicIqPayloadPb;

typedef struct _makesdr_RadioCacheDualPayloadPb {
    makesdr_RadioPayloadType payloadType;
    bool has_body;
    makesdr_DualIqBandSettingsCachePb body;
} makesdr_RadioCacheDualPayloadPb;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _makesdr_RadioPayloadType_MIN makesdr_RadioPayloadType_PAYLOAD_NONE
#define _makesdr_RadioPayloadType_MAX makesdr_RadioPayloadType_PAYLOAD_CACHE_DUAL
#define _makesdr_RadioPayloadType_ARRAYSIZE ((makesdr_RadioPayloadType)(makesdr_RadioPayloadType_PAYLOAD_CACHE_DUAL+1))

#define _makesdr_RadioPayloadPurpose_MIN makesdr_RadioPayloadPurpose_PURPOSE_NONE
#define _makesdr_RadioPayloadPurpose_MAX makesdr_RadioPayloadPurpose_PURPOSE_REPLACE
#define _makesdr_RadioPayloadPurpose_ARRAYSIZE ((makesdr_RadioPayloadPurpose)(makesdr_RadioPayloadPurpose_PURPOSE_REPLACE+1))

#define makesdr_RadioPayloadHeaderPb_payloadType_ENUMTYPE makesdr_RadioPayloadType


#define makesdr_BasicRxSettingsPayloadPb_purpose_ENUMTYPE makesdr_RadioPayloadPurpose

#define makesdr_BasicIqRxSettingsPayloadPb_purpose_ENUMTYPE makesdr_RadioPayloadPurpose

#define makesdr_DualIqRxSettingsPayloadPb_purpose_ENUMTYPE makesdr_RadioPayloadPurpose

#define makesdr_BasicRxTxSettingsPayloadPb_purpose_ENUMTYPE makesdr_RadioPayloadPurpose

#define makesdr_BasicIqRxTxSettingsPayloadPb_purpose_ENUMTYPE makesdr_RadioPayloadPurpose

#define makesdr_DualIqRxTxSettingsPayloadPb_purpose_ENUMTYPE makesdr_RadioPayloadPurpose

#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_purpose_ENUMTYPE makesdr_RadioPayloadPurpose


#define makesdr_RadioCacheBasicPayloadPb_payloadType_ENUMTYPE makesdr_RadioPayloadType

#define makesdr_RadioCacheBasicIqPayloadPb_payloadType_ENUMTYPE makesdr_RadioPayloadType

#define makesdr_RadioCacheDualPayloadPb_payloadType_ENUMTYPE makesdr_RadioPayloadType


/* Initializer values for message structs */
#define makesdr_RadioPayloadHeaderPb_init_default {_makesdr_RadioPayloadType_MIN}
#define makesdr_RadioPayloadBasePb_init_default  {false, makesdr_RadioPayloadHeaderPb_init_default}
#define makesdr_BasicRxSettingsPayloadPb_init_default {false, makesdr_RadioPayloadHeaderPb_init_default, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_BasicRxSettingsPb_init_default}
#define makesdr_BasicIqRxSettingsPayloadPb_init_default {false, makesdr_RadioPayloadHeaderPb_init_default, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_BasicIqRxSettingsPb_init_default}
#define makesdr_DualIqRxSettingsPayloadPb_init_default {false, makesdr_RadioPayloadHeaderPb_init_default, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_DualIqRxSettingsPb_init_default}
#define makesdr_BasicRxTxSettingsPayloadPb_init_default {false, makesdr_RadioPayloadHeaderPb_init_default, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_BasicRxTxSettingsPb_init_default}
#define makesdr_BasicIqRxTxSettingsPayloadPb_init_default {false, makesdr_RadioPayloadHeaderPb_init_default, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_BasicIqRxTxSettingsPb_init_default}
#define makesdr_DualIqRxTxSettingsPayloadPb_init_default {false, makesdr_RadioPayloadHeaderPb_init_default, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_DualIqRxTxSettingsPb_init_default}
#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_init_default {false, makesdr_RadioPayloadHeaderPb_init_default, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_SplitBandDualIqRxTxSettingsPb_init_default}
#define makesdr_RadioLookupPayloadPb_init_default {false, makesdr_RadioPayloadHeaderPb_init_default, false, makesdr_RadioLookupPb_init_default}
#define makesdr_RadioCacheBasicPayloadPb_init_default {_makesdr_RadioPayloadType_MIN, false, makesdr_BasicBandSettingsCachePb_init_default}
#define makesdr_RadioCacheBasicIqPayloadPb_init_default {_makesdr_RadioPayloadType_MIN, false, makesdr_BasicIqBandSettingsCachePb_init_default}
#define makesdr_RadioCacheDualPayloadPb_init_default {_makesdr_RadioPayloadType_MIN, false, makesdr_DualIqBandSettingsCachePb_init_default}
#define makesdr_RadioPayloadHeaderPb_init_zero   {_makesdr_RadioPayloadType_MIN}
#define makesdr_RadioPayloadBasePb_init_zero     {false, makesdr_RadioPayloadHeaderPb_init_zero}
#define makesdr_BasicRxSettingsPayloadPb_init_zero {false, makesdr_RadioPayloadHeaderPb_init_zero, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_BasicRxSettingsPb_init_zero}
#define makesdr_BasicIqRxSettingsPayloadPb_init_zero {false, makesdr_RadioPayloadHeaderPb_init_zero, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_BasicIqRxSettingsPb_init_zero}
#define makesdr_DualIqRxSettingsPayloadPb_init_zero {false, makesdr_RadioPayloadHeaderPb_init_zero, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_DualIqRxSettingsPb_init_zero}
#define makesdr_BasicRxTxSettingsPayloadPb_init_zero {false, makesdr_RadioPayloadHeaderPb_init_zero, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_BasicRxTxSettingsPb_init_zero}
#define makesdr_BasicIqRxTxSettingsPayloadPb_init_zero {false, makesdr_RadioPayloadHeaderPb_init_zero, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_BasicIqRxTxSettingsPb_init_zero}
#define makesdr_DualIqRxTxSettingsPayloadPb_init_zero {false, makesdr_RadioPayloadHeaderPb_init_zero, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_DualIqRxTxSettingsPb_init_zero}
#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_init_zero {false, makesdr_RadioPayloadHeaderPb_init_zero, _makesdr_RadioPayloadPurpose_MIN, false, makesdr_SplitBandDualIqRxTxSettingsPb_init_zero}
#define makesdr_RadioLookupPayloadPb_init_zero   {false, makesdr_RadioPayloadHeaderPb_init_zero, false, makesdr_RadioLookupPb_init_zero}
#define makesdr_RadioCacheBasicPayloadPb_init_zero {_makesdr_RadioPayloadType_MIN, false, makesdr_BasicBandSettingsCachePb_init_zero}
#define makesdr_RadioCacheBasicIqPayloadPb_init_zero {_makesdr_RadioPayloadType_MIN, false, makesdr_BasicIqBandSettingsCachePb_init_zero}
#define makesdr_RadioCacheDualPayloadPb_init_zero {_makesdr_RadioPayloadType_MIN, false, makesdr_DualIqBandSettingsCachePb_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define makesdr_RadioPayloadHeaderPb_payloadType_tag 1
#define makesdr_RadioPayloadBasePb_header_tag    1
#define makesdr_BasicRxSettingsPayloadPb_header_tag 1
#define makesdr_BasicRxSettingsPayloadPb_purpose_tag 2
#define makesdr_BasicRxSettingsPayloadPb_body_tag 3
#define makesdr_BasicIqRxSettingsPayloadPb_header_tag 1
#define makesdr_BasicIqRxSettingsPayloadPb_purpose_tag 2
#define makesdr_BasicIqRxSettingsPayloadPb_body_tag 3
#define makesdr_DualIqRxSettingsPayloadPb_header_tag 1
#define makesdr_DualIqRxSettingsPayloadPb_purpose_tag 2
#define makesdr_DualIqRxSettingsPayloadPb_body_tag 3
#define makesdr_BasicRxTxSettingsPayloadPb_header_tag 1
#define makesdr_BasicRxTxSettingsPayloadPb_purpose_tag 2
#define makesdr_BasicRxTxSettingsPayloadPb_body_tag 3
#define makesdr_BasicIqRxTxSettingsPayloadPb_header_tag 1
#define makesdr_BasicIqRxTxSettingsPayloadPb_purpose_tag 2
#define makesdr_BasicIqRxTxSettingsPayloadPb_body_tag 3
#define makesdr_DualIqRxTxSettingsPayloadPb_header_tag 1
#define makesdr_DualIqRxTxSettingsPayloadPb_purpose_tag 2
#define makesdr_DualIqRxTxSettingsPayloadPb_body_tag 3
#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_header_tag 1
#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_purpose_tag 2
#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_body_tag 3
#define makesdr_RadioLookupPayloadPb_header_tag  1
#define makesdr_RadioLookupPayloadPb_body_tag    2
#define makesdr_RadioCacheBasicPayloadPb_payloadType_tag 1
#define makesdr_RadioCacheBasicPayloadPb_body_tag 2
#define makesdr_RadioCacheBasicIqPayloadPb_payloadType_tag 1
#define makesdr_RadioCacheBasicIqPayloadPb_body_tag 2
#define makesdr_RadioCacheDualPayloadPb_payloadType_tag 1
#define makesdr_RadioCacheDualPayloadPb_body_tag 2

/* Struct field encoding specification for nanopb */
#define makesdr_RadioPayloadHeaderPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    payloadType,       1)
#define makesdr_RadioPayloadHeaderPb_CALLBACK NULL
#define makesdr_RadioPayloadHeaderPb_DEFAULT NULL

#define makesdr_RadioPayloadBasePb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1)
#define makesdr_RadioPayloadBasePb_CALLBACK NULL
#define makesdr_RadioPayloadBasePb_DEFAULT NULL
#define makesdr_RadioPayloadBasePb_header_MSGTYPE makesdr_RadioPayloadHeaderPb

#define makesdr_BasicRxSettingsPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UENUM,    purpose,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              3)
#define makesdr_BasicRxSettingsPayloadPb_CALLBACK NULL
#define makesdr_BasicRxSettingsPayloadPb_DEFAULT NULL
#define makesdr_BasicRxSettingsPayloadPb_header_MSGTYPE makesdr_RadioPayloadHeaderPb
#define makesdr_BasicRxSettingsPayloadPb_body_MSGTYPE makesdr_BasicRxSettingsPb

#define makesdr_BasicIqRxSettingsPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UENUM,    purpose,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              3)
#define makesdr_BasicIqRxSettingsPayloadPb_CALLBACK NULL
#define makesdr_BasicIqRxSettingsPayloadPb_DEFAULT NULL
#define makesdr_BasicIqRxSettingsPayloadPb_header_MSGTYPE makesdr_RadioPayloadHeaderPb
#define makesdr_BasicIqRxSettingsPayloadPb_body_MSGTYPE makesdr_BasicIqRxSettingsPb

#define makesdr_DualIqRxSettingsPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UENUM,    purpose,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              3)
#define makesdr_DualIqRxSettingsPayloadPb_CALLBACK NULL
#define makesdr_DualIqRxSettingsPayloadPb_DEFAULT NULL
#define makesdr_DualIqRxSettingsPayloadPb_header_MSGTYPE makesdr_RadioPayloadHeaderPb
#define makesdr_DualIqRxSettingsPayloadPb_body_MSGTYPE makesdr_DualIqRxSettingsPb

#define makesdr_BasicRxTxSettingsPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UENUM,    purpose,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              3)
#define makesdr_BasicRxTxSettingsPayloadPb_CALLBACK NULL
#define makesdr_BasicRxTxSettingsPayloadPb_DEFAULT NULL
#define makesdr_BasicRxTxSettingsPayloadPb_header_MSGTYPE makesdr_RadioPayloadHeaderPb
#define makesdr_BasicRxTxSettingsPayloadPb_body_MSGTYPE makesdr_BasicRxTxSettingsPb

#define makesdr_BasicIqRxTxSettingsPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UENUM,    purpose,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              3)
#define makesdr_BasicIqRxTxSettingsPayloadPb_CALLBACK NULL
#define makesdr_BasicIqRxTxSettingsPayloadPb_DEFAULT NULL
#define makesdr_BasicIqRxTxSettingsPayloadPb_header_MSGTYPE makesdr_RadioPayloadHeaderPb
#define makesdr_BasicIqRxTxSettingsPayloadPb_body_MSGTYPE makesdr_BasicIqRxTxSettingsPb

#define makesdr_DualIqRxTxSettingsPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UENUM,    purpose,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              3)
#define makesdr_DualIqRxTxSettingsPayloadPb_CALLBACK NULL
#define makesdr_DualIqRxTxSettingsPayloadPb_DEFAULT NULL
#define makesdr_DualIqRxTxSettingsPayloadPb_header_MSGTYPE makesdr_RadioPayloadHeaderPb
#define makesdr_DualIqRxTxSettingsPayloadPb_body_MSGTYPE makesdr_DualIqRxTxSettingsPb

#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UENUM,    purpose,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              3)
#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_CALLBACK NULL
#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_DEFAULT NULL
#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_header_MSGTYPE makesdr_RadioPayloadHeaderPb
#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_body_MSGTYPE makesdr_SplitBandDualIqRxTxSettingsPb

#define makesdr_RadioLookupPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              2)
#define makesdr_RadioLookupPayloadPb_CALLBACK NULL
#define makesdr_RadioLookupPayloadPb_DEFAULT NULL
#define makesdr_RadioLookupPayloadPb_header_MSGTYPE makesdr_RadioPayloadHeaderPb
#define makesdr_RadioLookupPayloadPb_body_MSGTYPE makesdr_RadioLookupPb

#define makesdr_RadioCacheBasicPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    payloadType,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              2)
#define makesdr_RadioCacheBasicPayloadPb_CALLBACK NULL
#define makesdr_RadioCacheBasicPayloadPb_DEFAULT NULL
#define makesdr_RadioCacheBasicPayloadPb_body_MSGTYPE makesdr_BasicBandSettingsCachePb

#define makesdr_RadioCacheBasicIqPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    payloadType,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              2)
#define makesdr_RadioCacheBasicIqPayloadPb_CALLBACK NULL
#define makesdr_RadioCacheBasicIqPayloadPb_DEFAULT NULL
#define makesdr_RadioCacheBasicIqPayloadPb_body_MSGTYPE makesdr_BasicIqBandSettingsCachePb

#define makesdr_RadioCacheDualPayloadPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    payloadType,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  body,              2)
#define makesdr_RadioCacheDualPayloadPb_CALLBACK NULL
#define makesdr_RadioCacheDualPayloadPb_DEFAULT NULL
#define makesdr_RadioCacheDualPayloadPb_body_MSGTYPE makesdr_DualIqBandSettingsCachePb

extern const pb_msgdesc_t makesdr_RadioPayloadHeaderPb_msg;
extern const pb_msgdesc_t makesdr_RadioPayloadBasePb_msg;
extern const pb_msgdesc_t makesdr_BasicRxSettingsPayloadPb_msg;
extern const pb_msgdesc_t makesdr_BasicIqRxSettingsPayloadPb_msg;
extern const pb_msgdesc_t makesdr_DualIqRxSettingsPayloadPb_msg;
extern const pb_msgdesc_t makesdr_BasicRxTxSettingsPayloadPb_msg;
extern const pb_msgdesc_t makesdr_BasicIqRxTxSettingsPayloadPb_msg;
extern const pb_msgdesc_t makesdr_DualIqRxTxSettingsPayloadPb_msg;
extern const pb_msgdesc_t makesdr_SplitBandDualIqRxTxSettingsPayloadPb_msg;
extern const pb_msgdesc_t makesdr_RadioLookupPayloadPb_msg;
extern const pb_msgdesc_t makesdr_RadioCacheBasicPayloadPb_msg;
extern const pb_msgdesc_t makesdr_RadioCacheBasicIqPayloadPb_msg;
extern const pb_msgdesc_t makesdr_RadioCacheDualPayloadPb_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define makesdr_RadioPayloadHeaderPb_fields &makesdr_RadioPayloadHeaderPb_msg
#define makesdr_RadioPayloadBasePb_fields &makesdr_RadioPayloadBasePb_msg
#define makesdr_BasicRxSettingsPayloadPb_fields &makesdr_BasicRxSettingsPayloadPb_msg
#define makesdr_BasicIqRxSettingsPayloadPb_fields &makesdr_BasicIqRxSettingsPayloadPb_msg
#define makesdr_DualIqRxSettingsPayloadPb_fields &makesdr_DualIqRxSettingsPayloadPb_msg
#define makesdr_BasicRxTxSettingsPayloadPb_fields &makesdr_BasicRxTxSettingsPayloadPb_msg
#define makesdr_BasicIqRxTxSettingsPayloadPb_fields &makesdr_BasicIqRxTxSettingsPayloadPb_msg
#define makesdr_DualIqRxTxSettingsPayloadPb_fields &makesdr_DualIqRxTxSettingsPayloadPb_msg
#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_fields &makesdr_SplitBandDualIqRxTxSettingsPayloadPb_msg
#define makesdr_RadioLookupPayloadPb_fields &makesdr_RadioLookupPayloadPb_msg
#define makesdr_RadioCacheBasicPayloadPb_fields &makesdr_RadioCacheBasicPayloadPb_msg
#define makesdr_RadioCacheBasicIqPayloadPb_fields &makesdr_RadioCacheBasicIqPayloadPb_msg
#define makesdr_RadioCacheDualPayloadPb_fields &makesdr_RadioCacheDualPayloadPb_msg

/* Maximum encoded size of messages (where known) */
#define MAKESDR_RADIOPAYLOADS_PB_H_MAX_SIZE      makesdr_RadioLookupPayloadPb_size
#define makesdr_BasicIqRxSettingsPayloadPb_size  402
#define makesdr_BasicIqRxTxSettingsPayloadPb_size 428
#define makesdr_BasicRxSettingsPayloadPb_size    270
#define makesdr_BasicRxTxSettingsPayloadPb_size  296
#define makesdr_RadioLookupPayloadPb_size        9057
#define makesdr_RadioPayloadBasePb_size          4
#define makesdr_RadioPayloadHeaderPb_size        2
#if defined(makesdr_DualIqRxSettingsPb_size)
#define makesdr_DualIqRxSettingsPayloadPb_size   (12 + makesdr_DualIqRxSettingsPb_size)
#endif
#if defined(makesdr_DualIqRxTxSettingsPb_size)
#define makesdr_DualIqRxTxSettingsPayloadPb_size (12 + makesdr_DualIqRxTxSettingsPb_size)
#endif
#if defined(makesdr_SplitBandDualIqRxTxSettingsPb_size)
#define makesdr_SplitBandDualIqRxTxSettingsPayloadPb_size (12 + makesdr_SplitBandDualIqRxTxSettingsPb_size)
#endif
#if defined(makesdr_BasicBandSettingsCachePb_size)
#define makesdr_RadioCacheBasicPayloadPb_size    (8 + makesdr_BasicBandSettingsCachePb_size)
#endif
#if defined(makesdr_BasicIqBandSettingsCachePb_size)
#define makesdr_RadioCacheBasicIqPayloadPb_size  (8 + makesdr_BasicIqBandSettingsCachePb_size)
#endif
#if defined(makesdr_DualIqBandSettingsCachePb_size)
#define makesdr_RadioCacheDualPayloadPb_size     (8 + makesdr_DualIqBandSettingsCachePb_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
